version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: taskpilot-app
    env_file: .env.docker
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    
  nginx:
    image: nginx:1.27-alpine
    container_name: taskpilot-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: postgres:16
    container_name: taskpilot-db
    environment:
      POSTGRES_DB: taskpilot
      POSTGRES_USER: taskpilot
      POSTGRES_PASSWORD: Pass1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: